"""add telegram_update_id to Message

Revision ID: f0c3e033b85c
Revises: a21189741ac6
Create Date: 2026-02-18 11:49:43.646866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c3e033b85c'
down_revision: Union[str, Sequence[str], None] = 'a21189741ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('telegram_update_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'telegram_update_id')
    # ### end Alembic commands ###
